/**
 * Catálogo completo de productos - Pinturas San Pedro
 * Optimizado para rendimiento con estructura de datos eficiente
 */

import type { Product, ProductCategory } from '@/lib/types'

export const productCategories: { value: ProductCategory; label: string }[] = [
  { value: 'vinilos', label: 'Vinilos' },
  { value: 'anticorrosivo', label: 'Anticorrosivo' },
  { value: 'esmaltes', label: 'Esmaltes' },
  { value: 'trafico-pesado', label: 'Tráfico Pesado' },
  { value: 'estucos', label: 'Estucos' },
  { value: 'impermeabilizante', label: 'Impermeabilizante' },
  { value: 'herramientas', label: 'Herramientas' },
  { value: 'rodillos', label: 'Rodillos' },
  { value: 'brochas', label: 'Brochas' },
]

export const products: Product[] = [
  // VINILOS
  {
    id: 'vinilo-acrilico',
    name: 'Vinilo acrílico',
    category: 'vinilos',
    image: '/productos/vinilo-acrilico.webp',
    description: 'Vinilo acrílico con acabado mate lavable, ideal para interiores. Con desempeño y cubrimiento, bajo aroma y nivelación.',
    characteristics: ['Acabado mate lavable', 'Con cubrimiento', 'Bajo aroma', 'Con nivelación'],
    presentations: ['Cuñete', 'Medio', 'Galón'],
    certifications: ['NTC 1335 (algunas referencias)'],
    colors: ['Blanco', 'Almendra', 'Rojo'],
  },
  {
    id: 'vinilo-semilavable',
    name: 'Vinilo tipo 2 Semilavable',
    category: 'vinilos',
    image: '/productos/vinilo-semilavable.webp',
    description: 'Vinilo con acabado mate, ideal para interiores. Con cubrimiento y rendimiento, bajo aroma.',
    characteristics: ['Acabado mate', 'Con cubrimiento', 'Bajo aroma', 'Opción semilavable'],
    presentations: ['Cuñete', 'Medio', 'Galón'],
    certifications: ['NTC 1335 (algunas referencias)'],
  },
  {
    id: 'vinilo-hidrofugado',
    name: 'Vinilo tipo coraza',
    category: 'vinilos',
    image: '/productos/vinilo-hidrofugado.webp',
    description: 'Pintura diluible en agua con acabado satinado, hidrofugable y con resistencia. Ideal para fachadas o uso interior con exigencias de impermeabilización y lavabilidad.',
    characteristics: ['Acabado satinado', 'Hidrofugable', 'Con resistencia', 'Fachadas o uso interior'],
    presentations: ['Cuñete', 'Medio', 'Galón'],
  },
  {
    id: 'vinilo-tipo-2-certificado',
    name: 'Vinilo tipo 2 certificado',
    category: 'vinilos',
    image: '/productos/vinilo-tipo-2-certificado.webp',
    description: 'Pintura económica con calidad para interiores. Ideal para proyectos con presupuesto ajustado sin comprometer la calidad.',
    characteristics: ['Económica', 'Con calidad', 'Fácil aplicación'],
    presentations: ['Cuñete', 'Medio', 'Galón'],
  },
  {
    id: 'vinilo-tipo-1-certificado',
    name: 'Vinilo acrílico tipo 1 certificado',
    category: 'vinilos',
    image: '/productos/vinilo-tipo-1-certificado.webp',
    description: 'Vinilo acrílico certificado con acabado mate lavable, ideal para interiores. Con desempeño y cubrimiento, bajo aroma y nivelación.',
    characteristics: ['Acabado mate lavable', 'Con cubrimiento', 'Bajo aroma', 'Con nivelación', 'Certificado'],
    presentations: ['Cuñete', 'Medio', 'Galón'],
    certifications: ['NTC 1335'],
  },
  {
    id: 'vinilo-tipo-3',
    name: 'Vinilo tipo 3',
    category: 'vinilos',
    image: '/productos/vinilo-tipo-3.webp',
    description: 'Pintura económica con calidad para interiores. Ideal para proyectos con presupuesto ajustado sin comprometer la calidad.',
    characteristics: ['Económica', 'Con calidad', 'Fácil aplicación'],
    presentations: ['Cuñete', 'Medio', 'Galón'],
  },

  // ANTICORROSIVO
  {
    id: 'anticorrosivo',
    name: 'Anticorrosivo',
    category: 'anticorrosivo',
    image: '/productos/anticorrosivo.webp',
    description: 'Producto diseñado con protección contra la oxidación y el desgaste.',
    characteristics: ['Protección contra oxidación', 'Mejora adhesión del esmalte', 'Secado rápido', 'Con resistencia'],
    presentations: ['Cuñete', 'Medio', 'Galón'],
    uses: ['Primera mano para superficies metálicas en interiores y exteriores', 'Ventanas, rejas, puentes, barandas', 'Estructuras metálicas con exposición ambiental moderada'],
    benefits: ['Previene la formación de óxido', 'Mejora la adhesión del esmalte', 'Fácil aplicación y secado rápido', 'Con resistencia y durabilidad'],
    application: 'Listo para usar. Aplicable con rodillo o brocha. Se disuelve con thinner o varsol.',
  },

  // ESMALTES
  {
    id: 'esmalte-especial',
    name: 'Esmalte Especial',
    category: 'esmaltes',
    image: '/productos/esmalte-especial.webp',
    description: 'Con protección y decoración de superficies de metal y madera.',
    characteristics: ['Con protección', 'Decoración', 'Durabilidad'],
    presentations: ['Cuñete', 'Galón', '1/4', '1/8'],
    uses: ['Rejas, puertas, ventanas', 'Marcos, persianas', 'Tuberías, zócalos'],
  },
  {
    id: 'esmalte-premium',
    name: 'Esmalte Premium',
    category: 'esmaltes',
    image: '/productos/esmalte-premium.webp',
    description: 'Con protección para superficies de metal y madera.',
    characteristics: ['Con protección', 'Con calidad', 'Con acabado'],
    presentations: ['Cuñete', 'Galón', '1/4', '1/8'],
    uses: ['Rejas, puertas, ventanas', 'Marcos, persianas', 'Tuberías, zócalos'],
  },
  {
    id: 'esmalte-tipo-1',
    name: 'Esmalte Tipo 1',
    category: 'esmaltes',
    image: '/productos/esmalte-tipo-1.webp',
    description: 'Pintar y proteger superficies de metal y madera.',
    characteristics: ['Protección', 'Decoración', 'Versatilidad'],
    presentations: ['Cuñete', 'Medio', '1/4'],
    uses: ['Rejas, puertas, ventanas', 'Marcos, persianas', 'Tuberías, zócalos'],
  },
  {
    id: 'esmalte-base-agua',
    name: 'Esmalte a base agua',
    category: 'esmaltes',
    image: '/productos/esmalte-base-agua.webp',
    description: 'Esmalte ecológico a base de agua para protección y decoración de superficies de metal y madera.',
    characteristics: ['A base de agua', 'Ecológico', 'Con protección', 'Fácil aplicación'],
    presentations: ['Cuñete', 'Medio', 'Galón'],
    uses: ['Rejas, puertas, ventanas', 'Marcos, persianas', 'Tuberías, zócalos'],
  },

  // TRÁFICO PESADO
  {
    id: 'trafico-pesado',
    name: 'Tráfico Pesado',
    category: 'trafico-pesado',
    image: '/productos/trafico-pesado.webp',
    description: 'Pintura con desempeño para señalización y demarcación de pavimentos.',
    characteristics: ['Con resistencia al desgaste', 'Secado rápido', 'Con durabilidad'],
    presentations: ['Cuñete', 'Galón', 'Medio Cuñete'],
    uses: ['Estacionamientos', 'Carreteras', 'Zonas industriales'],
  },

  // ESTUCOS
  {
    id: 'estuco-plastico-acrilico',
    name: 'Estuco Plástico Acrílico',
    category: 'estucos',
    image: '/productos/estuco-plastico-acrilico.webp',
    description: 'Producto de acabado liso para paredes.',
    characteristics: ['Acabado liso', 'Con adherencia', 'Fácil aplicación'],
    presentations: ['Cuñete', 'Medio', 'Galón'],
    uses: ['Paredes interiores', 'Superficies de madera en interiores', 'Aplicación sobre pañetes antes de vinilo o esmalte'],
  },
  {
    id: 'graniplas',
    name: 'Graniplas',
    category: 'estucos',
    image: '/productos/graniplas.webp',
    description: 'Revestimiento para acabados texturizados decorativos.',
    characteristics: ['Acabado texturizado', 'Decorativo', 'Resistente'],
    presentations: ['Cuñete', 'Medio', 'Galón'],
    uses: ['Interiores y exteriores', 'Acabados modernos y resistentes'],
  },
  {
    id: 'garraplast',
    name: 'Carraplast',
    category: 'estucos',
    image: '/productos/garraplast.webp',
    description: 'Revestimiento decorativo con adherencia y flexibilidad.',
    characteristics: ['Con adherencia', 'Flexibilidad', 'Decorativo'],
    presentations: ['Cuñete', 'Medio', 'Galón'],
    uses: ['Protección y embellecimiento de superficies'],
  },
  {
    id: 'pasta-acrilica',
    name: 'Pasta Acrílica',
    category: 'estucos',
    image: '/productos/pasta acrilica.webp',
    description: 'Producto para nivelar y preparar superficies antes de pintar.',
    characteristics: ['Nivelación', 'Preparación de superficies', 'Acabado uniforme'],
    presentations: ['Cuñete', 'Medio', 'Galón'],
    benefits: ['Garantiza un acabado uniforme y profesional', 'Mejora la apariencia final de la pintura'],
  },

  // IMPERMEABILIZANTE
  {
    id: 'impermeabilizante',
    name: 'Impermeabilizante',
    category: 'impermeabilizante',
    image: '/productos/Impermeabilizante_Uretanico.webp',
    description: 'Protege tu inversión con impermeabilizantes de alto rendimiento. Soluciones profesionales para evitar filtraciones, humedades y deterioro en techos, terrazas, muros y fachadas.',
    characteristics: ['Protección contra filtraciones', 'Alto rendimiento', 'Resistente a condiciones extremas', 'Alarga vida útil'],
    presentations: ['Cuñete', 'Medio', 'Galón'],
    benefits: ['Con durabilidad', 'Protección frente al clima y la humedad'],
  },

  // HERRAMIENTAS
  {
    id: 'recambio-rodillo',
    name: 'Recambios para rodillos',
    category: 'herramientas',
    image: '/productos/recambio-rodillo.webp',
    description: 'Recambios para rodillos en diferentes largos de pelo. Ideal para mantener tus rodillos en perfecto estado.',
    characteristics: ['Recambios disponibles', 'Diferentes largos', 'Fácil instalación'],
    presentations: ['Variedad de tamaños'],
    uses: ['Mantenimiento de rodillos', 'Reemplazo de recubrimiento'],
  },
  {
    id: 'bandeja-pintura',
    name: 'Bandejas',
    category: 'herramientas',
    image: '/productos/bandeja-pintura.webp',
    description: 'Recipiente estructurado para verter la pintura, permitiendo una carga controlada del rodillo.',
    characteristics: ['Carga controlada', 'Zona de descarga', 'Estructurado'],
    presentations: ['Estándar'],
    uses: ['Verter pintura', 'Carga de rodillos', 'Eliminar exceso'],
  },
  {
    id: 'cinta-enmascarar',
    name: 'Cinta de Enmascarar Cellux / Estándar',
    category: 'herramientas',
    image: '/productos/cinta-enmascarar.webp',
    description: 'Para trabajos de precisión y multipropósito, destacada por ser fácil de remover sin transferir pegante.',
    characteristics: ['Precisión', 'Multipropósito', 'Fácil de remover', 'No deja pegante'],
    presentations: ['24 mm x 40 yd', '40 mm x 40 mts'],
    uses: ['Trabajos de precisión', 'Protección de superficies', 'Líneas limpias'],
  },
  {
    id: 'plastico-protector',
    name: 'Lonas y plásticos protectores',
    category: 'herramientas',
    image: '/productos/plastico-protector.webp',
    description: 'Lonas y plásticos protectores para cubrir muebles, pisos y superficies durante trabajos de pintura.',
    characteristics: ['Protección completa', 'Resistentes', 'Reutilizables'],
    presentations: ['Variedad de tamaños'],
    uses: ['Protección de muebles', 'Cubrir pisos', 'Protección de superficies'],
  },
  {
    id: 'carton-corrugado',
    name: 'Cartón corrugado',
    category: 'herramientas',
    image: '/productos/carton-corrugado-Photoroom.webp',
    description: 'Cartón corrugado para protección de superficies durante trabajos de pintura.',
    characteristics: ['Protección de superficies', 'Resistente', 'Fácil de usar'],
    presentations: ['Variedad de tamaños'],
    uses: ['Protección de pisos', 'Cubrir muebles', 'Protección durante pintura'],
  },
  {
    id: 'disolvente',
    name: 'Disolventes',
    category: 'herramientas',
    image: '/productos/disolvente.webp',
    description: 'Limpieza de herramientas y preparación de superficies para un acabado óptimo.',
    characteristics: ['Limpieza de herramientas', 'Preparación de superficies'],
    presentations: ['Galón', 'Medio'],
    uses: ['Limpieza de herramientas', 'Preparación de superficies'],
  },
  {
    id: 'mezclador',
    name: 'Mezclador',
    category: 'herramientas',
    image: '/productos/mezclador.webp',
    description: 'Herramienta plástica diseñada para batir la pintura y asegurar que los pigmentos y resinas se integren perfectamente.',
    characteristics: ['Plástico', 'Integración de pigmentos', 'Fácil uso'],
  },
  {
    id: 'destapacuñete',
    name: 'Destapacuñete',
    category: 'herramientas',
    image: '/productos/destapacuñete.webp',
    description: 'Herramienta especializada para abrir las tapas de los cuñetes de pintura de forma rápida.',
    characteristics: ['Apertura rápida', 'Evita daños', 'Sin desperdicios'],
  },
  {
    id: 'espatula-plastica',
    name: 'Espátula Plástica',
    category: 'herramientas',
    image: '/productos/espatula-plastica.webp',
    description: 'Ligeras y flexibles, diseñadas específicamente para aplicar masilla y resanar agujeros en paredes.',
    characteristics: ['Ligera', 'Flexible', 'Para masilla'],
    presentations: ['4"', '5"', '6"'],
  },
  {
    id: 'espatula-acero-carbon',
    name: 'Espátula Boreal Acero al Carbón',
    category: 'herramientas',
    image: '/productos/espatula-acero-carbon.webp',
    description: 'Herramienta profesional de alta durabilidad para raspar superficies o aplicar materiales más densos.',
    characteristics: ['Alta durabilidad', 'Acero al carbón', 'Para raspar'],
    presentations: ['4"', '5"'],
  },
  {
    id: 'cepillo-alambre',
    name: 'Cepillo de Alambre Todo Uso',
    category: 'herramientas',
    image: '/productos/cepillo-alambre.webp',
    description: 'Con cerdas de acero, ideal para limpiar superficies oxidadas, remover pintura vieja o limpiar herramientas.',
    characteristics: ['Cerdas de acero', 'Remoción de óxido', 'Limpieza profunda'],
  },
  {
    id: 'lija-agua-negra',
    name: 'Lija de Agua Negra',
    category: 'herramientas',
    image: '/productos/lija-agua-negra.webp',
    description: 'Para lijado fino y acabados suaves usando agua como lubricante.',
    characteristics: ['Lijado fino', 'Acabados suaves', 'Uso con agua'],
    presentations: ['Granos 60 a 600'],
  },
  {
    id: 'lija-rojo-seco',
    name: 'Lija Roja en Seco',
    category: 'herramientas',
    image: '/productos/lija-rojo-seco.webp',
    description: 'Para desbaste y preparación de superficies de madera o pared sin necesidad de líquidos.',
    characteristics: ['Lijado en seco', 'Desbaste', 'Para madera o pared'],
    presentations: ['Granos 60 a 600'],
  },
  {
    id: 'pasta-pulir',
    name: 'Pasta de Pulir Mercury',
    category: 'herramientas',
    image: '/productos/pasta-pulir.webp',
    description: 'Compuesto abrasivo fino para dar brillo y acabado espejo a superficies pintadas.',
    characteristics: ['Abrasivo fino', 'Da brillo', 'Acabado espejo'],
    presentations: ['700 g'],
  },
  {
    id: 'disco-desbaste-pulido',
    name: 'Disco de Desbaste y Pulido',
    category: 'herramientas',
    image: '/productos/disco-desbaste-pulido.webp',
    description: 'Disco Flap Grano 60, diseñado para esmerilar y pulir metal (hierro) y madera.',
    characteristics: ['Grano 60', 'Esmerilar', 'Pulir metal y madera'],
  },
  {
    id: 'veteador-wi',
    name: 'Veteador WI 4+6"',
    category: 'herramientas',
    image: '/productos/veteador-wi.webp',
    description: 'Veteador mediano con aplicador de caucho. Ideal para crear efectos decorativos que imitan las vetas naturales de la madera.',
    characteristics: ['Efectos madera', 'Aplicador de caucho', 'Decorativo'],
    presentations: ['4+6"'],
  },
  {
    id: 'veteador-sbwr',
    name: 'Veteador SBWR-2.5"',
    category: 'herramientas',
    image: '/productos/veteador-sbwr.webp',
    description: 'Veteador de tamaño mediano con mango de madera. Específicamente diseñado para imitar motivos leñosos naturales.',
    characteristics: ['Motivos leñosos', 'Mango de madera', 'Decorativo'],
    presentations: ['2.5"'],
  },
  {
    id: 'veteador-sb-py',
    name: 'Veteador SB-PY 4"',
    category: 'herramientas',
    image: '/productos/veteador-sb-py.webp',
    description: 'Veteador de tamaño mediano con mango de plástico. Recomendado para lograr acabados decorativos tipo madera.',
    characteristics: ['Acabados tipo madera', 'Mango plástico', 'Decorativo'],
    presentations: ['4"'],
  },
  {
    id: 'veteador-sb-pb',
    name: 'Veteador SB-PB 5"',
    category: 'herramientas',
    image: '/productos/veteador-sb-pb.webp',
    description: 'Versión de tamaño grande con mango de madera. Ideal para superficies más amplias donde se requiera imitar el aspecto natural de la madera.',
    characteristics: ['Superficies amplias', 'Aspecto natural', 'Tamaño grande'],
    presentations: ['5"'],
  },

  // RODILLOS
  {
    id: 'rodillo-popular-9',
    name: 'Rodillo Popular 9"',
    category: 'rodillos',
    image: "/productos/rodillo-popular-9''.webp",
    description: 'Fabricado con sistema de termo fusión (sin costuras) para evitar que se suelte la felpa. Ofrece un óptimo rendimiento en la aplicación de pinturas a base de agua y vinilos.',
    characteristics: ['Sistema termo fusión', 'Sin costuras', 'Para base agua y vinilos'],
    presentations: ['9"'],
  },
  {
    id: 'rodillo-felpa-semiprofesional-9',
    name: 'Rodillo Felpa Semiprofesional 9"',
    category: 'rodillos',
    image: "/productos/rodillo-felpa-semiprofesional-9''.webp",
    description: 'Posee sistema de termo fusión y no tiene costuras. Está diseñado para ofrecer un acabado de calidad superior en superficies que requieran pinturas a base de agua o vinilos.',
    characteristics: ['Termo fusión', 'Sin costuras', 'Acabado superior', 'Para base agua'],
    presentations: ['9"'],
  },
  {
    id: 'rodillo-profesional-9-anillo',
    name: 'Rodillo Profesional 9" Anillo',
    category: 'rodillos',
    image: "/productos/rodillo-profesional-9''-anillo.webp",
    description: 'Elaborado con felpa industrial de alta densidad y sistema de termo fusión. No tiene costuras y no deja huella al pintar. Especial para pinturas base agua.',
    characteristics: ['Felpa industrial alta densidad', 'No deja huella', 'Termo fusión', 'Especial base agua'],
    presentations: ['9"'],
  },
  {
    id: 'rodillo-hilo-antigota-9',
    name: 'Rodillo Hilo Antigota 9"',
    category: 'rodillos',
    image: "/productos/rodillo-hilo-antigota-9''.webp",
    description: 'Fabricado con hilo de microfibra de última tecnología y termo fusión. Más duradero y ideal para pinturas complejas como epóxicas, de tráfico, esmaltes y vinilos.',
    characteristics: ['Hilo microfibra', 'Antigota', 'Mayor durabilidad', 'Para epóxicas y esmaltes'],
    presentations: ['9"'],
  },
  {
    id: 'rodillo-espuma-9',
    name: 'Rodillo Espuma 9"',
    category: 'rodillos',
    image: "/productos/rodillo-espuma-9''.webp",
    description: 'Hecho de espuma de poliuretano de alta calidad. Es la herramienta básica y efectiva para aplicaciones sencillas de pinturas a base de agua.',
    characteristics: ['Espuma poliuretano', 'Alta calidad', 'Para aplicaciones sencillas'],
    presentations: ['9"'],
  },
  {
    id: 'rodillo-teja-felpa-industrial',
    name: 'Rodillo Teja de Felpa Industrial',
    category: 'rodillos',
    image: '/productos/rodillo-teja-felpa-industrial.webp',
    description: 'Su estructura es ergonómica y está diseñada específicamente para adaptarse a la ondulación de las tejas tipo Eternit, facilitando el cubrimiento uniforme.',
    characteristics: ['Estructura ergonómica', 'Para tejas onduladas', 'Cubrimiento uniforme'],
    presentations: ['Estándar'],
  },
  {
    id: 'rodillo-mini-hilo-antigota',
    name: 'Mini Rodillos Hilo Antigota',
    category: 'rodillos',
    image: '/productos/rodillo-mini-hilo-antigota.webp',
    description: 'Versiones pequeñas con tecnología de microfibra y termo fusión. Ideales para marcos, esquinas y áreas de difícil acceso.',
    characteristics: ['Microfibra', 'Termo fusión', 'Para áreas difíciles', 'Epóxicas y esmaltes'],
    presentations: ['1"', '2"', '3"', '4"', '5"', '6"'],
  },
  {
    id: 'rodillo-junior',
    name: 'Rodillo Junior',
    category: 'rodillos',
    image: '/productos/rodillo-junior.webp',
    description: 'Versiones compactas del rodillo de felpa industrial con termo fusión. Sin costuras, para detalles en pinturas base agua.',
    characteristics: ['Compacto', 'Felpa industrial', 'Sin costuras', 'Para detalles'],
    presentations: ['7"', '5"', '3"'],
  },
  {
    id: 'rodillo-texturizador',
    name: 'Rodillo Texturizador',
    category: 'rodillos',
    image: '/productos/rodillo-texturizador.webp',
    description: 'Rodillo especial con relieve diseñado para crear acabados decorativos, texturas y efectos rústicos en paredes o techos.',
    characteristics: ['Con relieve', 'Acabados decorativos', 'Efectos rústicos'],
    presentations: ['9"', '7"', '5"', '3"'],
  },
  {
    id: 'rodillo-epoxico-9',
    name: 'Rodillo Epóxico 9"',
    category: 'rodillos',
    image: "/productos/rodillo-epoxico-9''.webp",
    description: 'Reforzado con termo fusión para resistir los químicos de las pinturas epóxicas, de tráfico y esmaltes, asegurando que la felpa no se desprenda.',
    characteristics: ['Resistente a químicos', 'Para epóxicas y tráfico', 'Felpa asegurada'],
    presentations: ['9"'],
  },
  {
    id: 'rodillo-teja-ovejero',
    name: 'Rodillo Teja Ovejero',
    category: 'rodillos',
    image: '/productos/rodillo-teja-ovejero.webp',
    description: 'Similar al de felpa industrial pero con material "ovejero" para una mayor carga de pintura en superficies irregulares de tejas.',
    characteristics: ['Material ovejero', 'Mayor carga de pintura', 'Para superficies irregulares'],
    presentations: ['Estándar'],
  },
  {
    id: 'rodillo-felpa-ovejera-9',
    name: 'Rodillo Felpa Ovejera 9"',
    category: 'rodillos',
    image: "/productos/rodillo-felpa-ovejera-9''.webp",
    description: 'Rodillo de alta capacidad de absorción con sistema de termo fusión, ideal para cubrir grandes áreas con pintura base agua rápidamente.',
    characteristics: ['Alta absorción', 'Termo fusión', 'Para grandes áreas'],
    presentations: ['9"'],
  },

  // BROCHAS
  {
    id: 'brocha-cerda-popular',
    name: 'Brocha Cerda Popular',
    category: 'brochas',
    image: '/productos/brocha-cerda-popular.webp',
    description: 'Es una brocha versátil y económica diseñada para aplicar toda clase de pinturas en trabajos generales.',
    characteristics: ['Versátil', 'Económica', 'Para trabajos generales'],
    presentations: ['2 1/2"', '3"', '4"'],
  },
  {
    id: 'brocha-cerda-premium',
    name: 'Brocha Cerda Premium',
    category: 'brochas',
    image: '/productos/brocha-cerda-premium.webp',
    description: 'Se distingue por su empaque rojo. Es de calidad superior, con mejor retención de pintura y apta para acabados exigentes con cualquier tipo de pintura.',
    characteristics: ['Calidad superior', 'Mejor retención', 'Para acabados exigentes'],
    presentations: ['1/2"', '1"', '1 1/2"', '2"', '2 1/2"', '3"', '4"', '5"'],
  },
]
