/**
 * Catálogo completo de productos - Pinturas San Pedro
 * Optimizado para rendimiento con estructura de datos eficiente
 */

import type { Product, ProductCategory } from '@/lib/types'

export const productCategories: { value: ProductCategory; label: string }[] = [
  { value: 'vinilos', label: 'Vinilos' },
  { value: 'anticorrosivo', label: 'Anticorrosivo' },
  { value: 'esmaltes', label: 'Esmaltes' },
  { value: 'trafico-pesado', label: 'Tráfico Pesado' },
  { value: 'estucos', label: 'Estucos' },
  { value: 'impermeabilizante', label: 'Impermeabilizante' },
  { value: 'herramientas', label: 'Herramientas' },
  { value: 'rodillos', label: 'Rodillos' },
  { value: 'brochas', label: 'Brochas' },
]

export const products: Product[] = [
  // VINILOS
  {
    id: 'vinilo-acrilico',
    name: 'Vinilo acrílico',
    category: 'vinilos',
    image: '/productos/vinilo-acrilico.webp',
    description: 'Pintura acrílica de acabado mate diseñada para ofrecer alta cobertura y durabilidad en espacios interiores.',
    characteristics: ['Acabado mate lavable', 'Alto cubrimiento', 'Bajo olor', 'Excelente nivelación'],
    presentations: ['Cuñete', 'Medio', 'Galón'],
    certifications: ['NTC 1335 (algunas referencias)'],
    colors: ['Blanco', 'Almendra', 'Rojo'],
  },
  {
    id: 'vinilo-semilavable',
    name: 'Vinilo tipo 2 Semilavable',
    category: 'vinilos',
    image: '/productos/vinilo-semilavable.webp',
    description: 'Pintura para interiores con acabado mate, desarrollada para proporcionar un cubrimiento eficiente y un rendimiento superior en cada aplicación.',
    characteristics: ['Acabado mate', 'Buen cubrimiento', 'Rendimiento óptimo', 'Bajo olor', 'Superficies uniformes'],
    presentations: ['Cuñete', 'Medio', 'Galón'],
    certifications: ['NTC 1335 (algunas referencias)'],
  },
  {
    id: 'vinilo-hidrofugado',
    name: 'Vinilo tipo coraza',
    category: 'vinilos',
    image: '/productos/vinilo-hidrofugado.webp',
    description: 'Pintura de alto rendimiento con acabado satinado y tecnología hidrófuga, ideal para proteger fachadas y muros bajo condiciones de humedad.',
    characteristics: ['Acabado satinado', 'Propiedades hidrofugantes', 'Alta resistencia a la intemperie', 'Uso en fachadas e interiores'],
    presentations: ['Cuñete', 'Medio', 'Galón'],
  },
  {
    id: 'vinilo-tipo-2-certificado',
    name: 'Vinilo tipo 2 certificado',
    category: 'vinilos',
    image: '/productos/vinilo-tipo-2-certificado.webp',
    description: 'Pintura económica de calidad certificada para interiores, ideal para proyectos que requieren un balance entre presupuesto y buen acabado.',
    characteristics: ['Costo eficiente', 'Calidad certificada', 'Fácil de aplicar'],
    presentations: ['Cuñete', 'Medio', 'Galón'],
  },
  {
    id: 'vinilo-tipo-1-certificado',
    name: 'Vinilo acrílico tipo 1 certificado',
    category: 'vinilos',
    image: '/productos/vinilo-tipo-1-certificado.webp',
    description: 'Producto acrílico de nivel superior con certificación de calidad, diseñado para obtener acabados profesionales de gran resistencia y lavabilidad.',
    characteristics: ['Acabado mate lavable', 'Cubrimiento excepcional', 'Bajo olor', 'Nivelación profesional', 'Certificación NTC 1335'],
    presentations: ['Cuñete', 'Medio', 'Galón'],
    certifications: ['NTC 1335'],
  },
  {
    id: 'vinilo-tipo-3',
    name: 'Vinilo tipo 3',
    category: 'vinilos',
    image: '/productos/vinilo-tipo-3.webp',
    description: 'Pintura básica de alta rotación para techos o primeras manos, ofreciendo una solución rentable para la renovación de espacios.',
    characteristics: ['Económica', 'Ideal para techos', 'Aplicación sencilla'],
    presentations: ['Cuñete', 'Medio', 'Galón'],
  },

  // ANTICORROSIVO
  {
    id: 'anticorrosivo',
    name: 'Anticorrosivo',
    category: 'anticorrosivo',
    image: '/productos/anticorrosivo.webp',
    description: 'Pintura técnica formulada para detener la progresión de la oxidación y proteger estructuras metálicas en diversos entornos.',
    characteristics: ['Protección contra la corrosión', 'Base para esmaltes', 'Resistencia climática'],
    presentations: ['Cuñete', 'Medio', 'Galón'],
    uses: ['Primera mano para superficies metálicas en interiores y exteriores', 'Ventanas, rejas, puentes, barandas', 'Estructuras metálicas con exposición ambiental moderada'],
    benefits: ['Previene la formación de óxido', 'Mejora la adhesión del esmalte', 'Fácil aplicación', 'Con resistencia y durabilidad'],
    application: 'Listo para usar. Aplicable con rodillo o brocha. Se disuelve con thinner o varsol.',
  },

  // ESMALTES
  {
    id: 'esmalte-especial',
    name: 'Esmalte Especial',
    category: 'esmaltes',
    image: '/productos/esmalte-especial.webp',
    description: 'Esmalte sintético de uso general diseñado para el embellecimiento y la protección duradera de elementos en metal y madera.',
    characteristics: ['Protección duradera', 'Acabado decorativo', 'Alta adherencia'],
    presentations: ['Cuñete', 'Galón', '1/4', '1/8'],
    uses: ['Rejas, puertas, ventanas', 'Marcos, persianas', 'Tuberías, zócalos'],
  },
  {
    id: 'esmalte-premium',
    name: 'Esmalte Premium',
    category: 'esmaltes',
    image: '/productos/esmalte-premium.webp',
    description: 'Esmalte de calidad superior que proporciona un acabado estético impecable y una barrera protectora reforzada contra el desgaste.',
    characteristics: ['Protección de alto nivel', 'Excelente acabado', 'Calidad premium'],
    presentations: ['Cuñete', 'Galón', '1/4', '1/8'],
    uses: ['Rejas, puertas, ventanas', 'Marcos, persianas', 'Tuberías, zócalos'],
  },
  {
    id: 'esmalte-tipo-1',
    name: 'Esmalte Tipo 1',
    category: 'esmaltes',
    image: '/productos/esmalte-tipo-1.webp',
    description: 'Pintura versátil enfocada en el mantenimiento estándar de superficies metálicas y de madera con resultados consistentes.',
    characteristics: ['Protección estándar', 'Versatilidad de uso', 'Resultados uniformes'],
    presentations: ['Cuñete', 'Medio', '1/4'],
    uses: ['Rejas, puertas, ventanas', 'Marcos, persianas', 'Tuberías, zócalos'],
  },
  {
    id: 'esmalte-base-agua',
    name: 'Esmalte a base agua',
    category: 'esmaltes',
    image: '/productos/esmalte-base-agua.webp',
    description: 'Esmalte ecológico formulado sin solventes agresivos, ideal para proyectos sostenibles que requieren protección en metal y madera.',
    characteristics: ['Fórmula base agua', 'Bajo impacto ambiental', 'Fácil limpieza', 'Protección efectiva'],
    presentations: ['Cuñete', 'Medio', 'Galón'],
    uses: ['Rejas, puertas, ventanas', 'Marcos, persianas', 'Tuberías, zócalos'],
  },

  // TRÁFICO PESADO
  {
    id: 'trafico-pesado',
    name: 'Tráfico Pesado',
    category: 'trafico-pesado',
    image: '/productos/trafico-pesado.webp',
    description: 'Pintura de alta resistencia diseñada para resistir el roce constante y las condiciones climáticas en la demarcación vial.',
    characteristics: ['Resistencia al tráfico', 'Secado extra rápido', 'Larga durabilidad'],
    presentations: ['Cuñete', 'Galón', 'Medio Cuñete'],
    uses: ['Estacionamientos', 'Carreteras', 'Zonas industriales'],
  },

  // ESTUCOS
  {
    id: 'estuco-plastico-acrilico',
    name: 'Estuco Plástico Acrílico',
    category: 'estucos',
    image: '/productos/estuco-plastico-acrilico.webp',
    description: 'Masa lista para suavizar paredes y ocultar imperfecciones, proporcionando la base perfecta para cualquier tipo de pintura.',
    characteristics: ['Acabado liso premium', 'Alta adherencia', 'Lijado sencillo'],
    presentations: ['Cuñete', 'Medio', 'Galón'],
    uses: ['Paredes interiores', 'Superficies de madera en interiores', 'Aplicación sobre pañetes antes de vinilo o esmalte'],
  },
  {
    id: 'graniplast',
    name: 'Graniplast',
    category: 'estucos',
    image: '/productos/graniplast.webp',
    description: 'Revestimiento plástico que permite crear texturas decorativas resistentes a la intemperie y de gran impacto visual.',
    characteristics: ['Textura decorativa', 'Resistencia exterior', 'Gran durabilidad'],
    presentations: ['Cuñete', 'Medio', 'Galón'],
    uses: ['Interiores y exteriores', 'Acabados modernos y resistentes'],
  },
  {
    id: 'garraplast',
    name: 'Carraplast',
    category: 'estucos',
    image: '/productos/garraplast.webp',
    description: 'Revestimiento versátil diseñado para ofrecer acabados flexibles y de alta adherencia en muros exteriores e interiores.',
    characteristics: ['Alta flexibilidad', 'Excelente adherencia', 'Variedad de acabados'],
    presentations: ['Cuñete', 'Medio', 'Galón'],
    uses: ['Protección y embellecimiento de superficies'],
  },
  {
    id: 'pasta-acrilica',
    name: 'Pasta Acrílica',
    category: 'estucos',
    image: '/productos/pasta acrilica.webp',
    description: 'Pasta especializada para la preparación técnica de superficies, asegurando un plano uniforme antes de los acabados finales.',
    characteristics: ['Nivelación de superficies', 'Base técnica', 'Acabado uniforme'],
    presentations: ['Cuñete', 'Medio', 'Galón'],
    benefits: ['Garantiza un acabado uniforme y profesional', 'Mejora la apariencia final de la pintura'],
  },

  // IMPERMEABILIZANTE
  {
    id: 'impermeabilizante',
    name: 'Impermeabilizante',
    category: 'impermeabilizante',
    image: '/productos/Impermeabilizante_Uretanico.webp',
    description: 'Sistema de protección hidrófuga diseñado para sellar superficies y prevenir filtraciones críticas en cubiertas y fachadas.',
    characteristics: ['Barrera contra humedad', 'Alto rendimiento elástico', 'Resistencia a climas extremos', 'Protección estructural'],
    presentations: ['Cuñete', 'Medio', 'Galón'],
    benefits: ['Con durabilidad', 'Protección frente al clima y la humedad'],
  },

  // HERRAMIENTAS
  {
    id: 'recambio-rodillo',
    name: 'Recambios para rodillos',
    category: 'herramientas',
    image: '/productos/recambio-rodillo.webp',
    description: 'Repuestos fabricados con diferentes largos de lana, ideales para renovar el rodillo y mantener un acabado uniforme.',
    characteristics: ['Variedad de fibras', 'Fácil instalación', 'Renovación de herramienta'],
    presentations: ['Variedad de tamaños'],
    uses: ['Mantenimiento de rodillos', 'Reemplazo de recubrimiento'],
  },
  {
    id: 'bandeja-pintura',
    name: 'Bandejas',
    category: 'herramientas',
    image: '/productos/bandeja-pintura.webp',
    description: 'Recipiente estructurado que facilita la distribución uniforme de la pintura y permite una carga controlada del rodillo.',
    characteristics: ['Carga equilibrada', 'Zona de descarga integrada', 'Estructura resistente'],
    presentations: ['Estándar'],
    uses: ['Verter pintura', 'Carga de rodillos', 'Eliminar exceso'],
  },
  {
    id: 'cinta-enmascarar',
    name: 'Cinta de Enmascarar Cellux / Estándar',
    category: 'herramientas',
    image: '/productos/cinta-enmascarar.webp',
    description: 'Cinta adhesiva de alta precisión diseñada para proteger áreas específicas y obtener líneas de pintura limpias sin dejar residuos.',
    characteristics: ['Alta precisión', 'Uso multipropósito', 'Remoción limpia y sencilla'],
    presentations: ['24 mm x 40 yd', '40 mm x 40 mts'],
    uses: ['Trabajos de precisión', 'Protección de superficies', 'Líneas limpias'],
  },
  {
    id: 'plastico-protector',
    name: 'Lonas y plásticos protectores',
    category: 'herramientas',
    image: '/productos/plastico-protector.webp',
    description: 'Cubiertas resistentes diseñadas para proteger muebles y pisos de salpicaduras, polvo y manchas durante trabajos de pintura.',
    characteristics: ['Protección integral', 'Material resistente', 'Reutilizable'],
    presentations: ['Variedad de tamaños'],
    uses: ['Protección de muebles', 'Cubrir pisos', 'Protección de superficies'],
  },
  {
    id: 'carton-corrugado',
    name: 'Cartón corrugado',
    category: 'herramientas',
    image: '/productos/carton-corrugado-Photoroom.webp',
    description: 'Material de protección robusto utilizado para cubrir pisos y superficies amplias durante procesos de remodelación y pintura.',
    characteristics: ['Protección de alto impacto', 'Fácil despliegue', 'Resistencia al tráfico'],
    presentations: ['Variedad de tamaños'],
    uses: ['Protección de pisos', 'Cubrir muebles', 'Protección durante pintura'],
  },
  {
    id: 'disolvente',
    name: 'Disolventes',
    category: 'herramientas',
    image: '/productos/disolvente.webp',
    description: 'Sustancia especializada diseñada para la dilución de pinturas, limpieza profunda de herramientas y preparación técnica de superficies.',
    characteristics: ['Limpieza efectiva', 'Dilución controlada', 'Uso técnico'],
    presentations: ['Galón', 'Medio'],
    uses: ['Limpieza de herramientas', 'Preparación de superficies'],
  },
  {
    id: 'mezclador',
    name: 'Mezclador',
    category: 'herramientas',
    image: '/productos/mezclador.webp',
    description: 'Accesorio ergonómico diseñado para batir la pintura, asegurando una integración completa de pigmentos y resinas.',
    characteristics: ['Mezcla homogénea', 'Material plástico duradero', 'Fácil manejo'],
  },
  {
    id: 'destapacuñete',
    name: 'Destapacuñete',
    category: 'herramientas',
    image: '/productos/destapacuñete.webp',
    description: 'Herramienta práctica fabricada para abrir envases de gran tamaño de manera segura, rápida y sin desperdicios.',
    characteristics: ['Apertura de seguridad', 'Prevención de daños al envase', 'Uso profesional'],
  },
  {
    id: 'espatula-plastica',
    name: 'Espátula Plástica',
    category: 'herramientas',
    image: '/productos/espatula-plastica.webp',
    description: 'Herramientas ligeras y flexibles ideales para la aplicación de masilla y el resane de pequeñas imperfecciones en muros.',
    characteristics: ['Alta flexibilidad', 'Peso ligero', 'Ideal para resanes'],
    presentations: ['4"', '5"', '6"'],
  },
  {
    id: 'espatula-acero-carbon',
    name: 'Espátula Boreal Acero al Carbón',
    category: 'herramientas',
    image: '/productos/espatula-acero-carbon.webp',
    description: 'Herramienta profesional de alta resistencia diseñada para raspar superficies difíciles o aplicar materiales de alta densidad.',
    characteristics: ['Durabilidad extrema', 'Acero al carbón forjado', 'Uso pesado'],
    presentations: ['4"', '5"'],
  },
  {
    id: 'cepillo-alambre',
    name: 'Cepillo de Alambre Todo Uso',
    category: 'herramientas',
    image: '/productos/cepillo-alambre.webp',
    description: 'Cepillo de cerdas metálicas diseñado para la remoción profunda de óxido, pintura vieja y limpieza técnica de herramientas.',
    characteristics: ['Remoción de corrosión', 'Cerdas de alta resistencia', 'Limpieza profunda'],
  },
  {
    id: 'lija-agua-negra',
    name: 'Lija de Agua Negra',
    category: 'herramientas',
    image: '/productos/lija-agua-negra.webp',
    description: 'Material abrasivo de grano fino diseñado para procesos de lijado que requieren lubricación con agua para obtener acabados extra suaves.',
    characteristics: ['Lijado de precisión', 'Acabado terso', 'Uso húmedo'],
    presentations: ['Granos 60 a 600'],
  },
  {
    id: 'lija-rojo-seco',
    name: 'Lija Roja en Seco',
    category: 'herramientas',
    image: '/productos/lija-rojo-seco.webp',
    description: 'Material abrasivo optimizado para procesos de desbaste y nivelación de madera o muros sin necesidad de utilizar líquidos.',
    characteristics: ['Desbaste eficiente', 'Uso en seco', 'Especial para madera y muro'],
    presentations: ['Granos 60 a 600'],
  },
  {
    id: 'pasta-pulir',
    name: 'Pasta de Pulir Mercury',
    category: 'herramientas',
    image: '/productos/pasta-pulir.webp',
    description: 'Compuesto abrasivo de alta gama desarrollado para restaurar el brillo y proporcionar un acabado espejo en superficies pintadas.',
    characteristics: ['Brillo intenso', 'Acabado tipo espejo', 'Abrasión controlada'],
    presentations: ['700 g'],
  },
  {
    id: 'disco-desbaste-pulido',
    name: 'Disco de Desbaste y Pulido',
    category: 'herramientas',
    image: '/productos/disco-desbaste-pulido.webp',
    description: 'Disco abrasivo especializado para procesos de esmerilado, pulido y nivelación de superficies metálicas y de madera.',
    characteristics: ['Grano 60 optimizado', 'Uso dual metal/madera', 'Desbaste rápido'],
  },
  {
    id: 'veteador-wi',
    name: 'Veteador WI 4+6"',
    category: 'herramientas',
    image: '/productos/veteador-wi.webp',
    description: 'Herramienta decorativa con aplicador de caucho diseñada para simular las vetas naturales de la madera en diversas superficies.',
    characteristics: ['Efecto madera realista', 'Caucho flexible', 'Fácil de limpiar'],
    presentations: ['4+6"'],
  },
  {
    id: 'veteador-sbwr',
    name: 'Veteador SBWR-2.5"',
    category: 'herramientas',
    image: '/productos/veteador-sbwr.webp',
    description: 'Herramienta de acabado equipada con mango de madera, ideal para replicar motivos leñosos con gran detalle decorativo.',
    characteristics: ['Detalle definido', 'Agarre ergonómico', 'Larga durabilidad'],
    presentations: ['2.5"'],
  },
  {
    id: 'veteador-sb-py',
    name: 'Veteador SB-PY 4"',
    category: 'herramientas',
    image: '/productos/veteador-sb-py.webp',
    description: 'Accesorio decorativo con mango ergonómico diseñado para lograr acabados que imitan la apariencia de maderas naturales.',
    characteristics: ['Acabado tipo madera', 'Mango de alta resistencia', 'Versatilidad'],
    presentations: ['4"'],
  },
  {
    id: 'veteador-sb-pb',
    name: 'Veteador SB-PB 5"',
    category: 'herramientas',
    image: '/productos/veteador-sb-pb.webp',
    description: 'Herramienta de gran tamaño diseñada para imitar vetas de madera en áreas extensas de forma rápida y eficiente.',
    characteristics: ['Cobertura amplia', 'Efecto natural', 'Ideal para grandes áreas'],
    presentations: ['5"'],
  },

  // RODILLOS
  {
    id: 'rodillo-popular-9',
    name: 'Rodillo Popular 9"',
    category: 'rodillos',
    image: "/productos/rodillo-popular-9''.webp",
    description: 'Herramienta de aplicación fabricada con sistema de termo fusión que garantiza durabilidad y un rendimiento constante en pinturas base agua.',
    characteristics: ['Termo fusión sin costuras', 'Alta durabilidad de felpa', 'Ideal para vinilos'],
    presentations: ['9"'],
  },
  {
    id: 'rodillo-felpa-semiprofesional-9',
    name: 'Rodillo Felpa Semiprofesional 9"',
    category: 'rodillos',
    image: "/productos/rodillo-felpa-semiprofesional-9''.webp",
    description: 'Rodillo de alta calidad diseñado para proporcionar acabados superiores en superficies lisas o semirrugosas con pinturas base agua.',
    characteristics: ['Felpa seleccionada', 'Acabado de alta gama', 'Sin desprendimiento'],
    presentations: ['9"'],
  },
  {
    id: 'rodillo-profesional-9-anillo',
    name: 'Rodillo Profesional 9" Anillo',
    category: 'rodillos',
    image: "/productos/rodillo-profesional-9''-anillo.webp",
    description: 'Herramienta profesional con felpa de alta densidad desarrollada para obtener coberturas uniformes sin dejar huellas en la superficie.',
    characteristics: ['Densidad industrial', 'Zero huella', 'Carga máxima de pintura'],
    presentations: ['9"'],
  },
  {
    id: 'rodillo-hilo-antigota-9',
    name: 'Rodillo Hilo Antigota 9"',
    category: 'rodillos',
    image: "/productos/rodillo-hilo-antigota-9''.webp",
    description: 'Rodillo de alta tecnología fabricado con microfibra diseñado para minimizar el salpicado y maximizar la descarga de pintura técnica.',
    characteristics: ['Tecnología antigota', 'Microfibra avanzada', 'Compatible con epóxicos'],
    presentations: ['9"'],
  },
  {
    id: 'rodillo-espuma-9',
    name: 'Rodillo Espuma 9"',
    category: 'rodillos',
    image: "/productos/rodillo-espuma-9''.webp",
    description: 'Herramienta básica y ligera fabricada en poliuretano, ideal para aplicaciones sencillas y retoques rápidos con pinturas base agua.',
    characteristics: ['Espuma de alta porosidad', 'Peso ligero', 'Económico y efectivo'],
    presentations: ['9"'],
  },
  {
    id: 'rodillo-teja-felpa-industrial',
    name: 'Rodillo Teja de Felpa Industrial',
    category: 'rodillos',
    image: '/productos/rodillo-teja-felpa-industrial.webp',
    description: 'Rodillo ergonómico con diseño especializado para adaptarse a la forma ondulada de las tejas, facilitando un cubrimiento homogéneo.',
    characteristics: ['Forma anatómica para teja', 'Aplicación ergonómica', 'Cubrimiento total'],
    presentations: ['Estándar'],
  },
  {
    id: 'rodillo-mini-hilo-antigota',
    name: 'Mini Rodillos Hilo Antigota',
    category: 'rodillos',
    image: '/productos/rodillo-mini-hilo-antigota.webp',
    description: 'Mini rodillos de microfibra diseñados para trabajar con precisión en marcos, esquinas y áreas de difícil acceso.',
    characteristics: ['Precisión en detalles', 'Fibras antigota', 'Uso en espacios reducidos'],
    presentations: ['1"', '2"', '3"', '4"', '5"', '6"'],
  },
  {
    id: 'rodillo-junior',
    name: 'Rodillo Junior',
    category: 'rodillos',
    image: '/productos/rodillo-junior.webp',
    description: 'Versión compacta del rodillo de felpa industrial, ideal para realizar detalles y acabados finales en espacios reducidos.',
    characteristics: ['Tamaño compacto', 'Felpa industrial resistente', 'Acabado detallado'],
    presentations: ['7"', '5"', '3"'],
  },
  {
    id: 'rodillo-texturizador',
    name: 'Rodillo Texturizador',
    category: 'rodillos',
    image: '/productos/rodillo-texturizador.webp',
    description: 'Herramienta con relieve diseñada para crear efectos decorativos rústicos y texturas personalizadas en paredes y techos.',
    characteristics: ['Efecto texturizado', 'Relieve definido', 'Versatilidad creativa'],
    presentations: ['9"', '7"', '5"', '3"'],
  },
  {
    id: 'rodillo-epoxico-9',
    name: 'Rodillo Epóxico 9"',
    category: 'rodillos',
    image: "/productos/rodillo-epoxico-9''.webp",
    description: 'Herramienta reforzada diseñada para resistir componentes químicos agresivos presentes en pinturas epóxicas y de tráfico.',
    characteristics: ['Resistencia química', 'Fijación de felpa extrema', 'Uso industrial'],
    presentations: ['9"'],
  },
  {
    id: 'rodillo-teja-ovejero',
    name: 'Rodillo Teja Ovejero',
    category: 'rodillos',
    image: '/productos/rodillo-teja-ovejero.webp',
    description: 'Rodillo de alta carga con material ovejero diseñado para cubrir eficazmente las irregularidades de tejas y superficies muy rugosas.',
    characteristics: ['Carga máxima de pintura', 'Adaptación a rugosidades', 'Uso en exteriores'],
    presentations: ['Estándar'],
  },
  {
    id: 'rodillo-felpa-ovejera-9',
    name: 'Rodillo Felpa Ovejera 9"',
    category: 'rodillos',
    image: "/productos/rodillo-felpa-ovejera-9''.webp",
    description: 'Herramienta de alta absorción diseñada para la aplicación rápida y eficiente de pintura en superficies de gran extensión.',
    characteristics: ['Absorción superior', 'Rapidez de cobertura', 'Uso en muros amplios'],
    presentations: ['9"'],
  },

  // BROCHAS
  {
    id: 'brocha-cerda-popular',
    name: 'Brocha Cerda Popular',
    category: 'brochas',
    image: '/productos/brocha-cerda-popular.webp',
    description: 'Herramienta versátil y económica diseñada para la aplicación de diversos tipos de pintura en tareas de mantenimiento general.',
    characteristics: ['Polivalencia de uso', 'Cerdas equilibradas', 'Costo accesible'],
    presentations: ['2 1/2"', '3"', '4"'],
  },
  {
    id: 'brocha-cerda-premium',
    name: 'Brocha Cerda Premium',
    category: 'brochas',
    image: '/productos/brocha-cerda-premium.webp',
    description: 'Brocha de calidad superior diseñada para ofrecer una excelente retención de pintura y acabados profesionales en cualquier superficie.',
    characteristics: ['Retención de carga óptima', 'Acabado sin rayas', 'Durabilidad profesional'],
    presentations: ['1/2"', '1"', '1 1/2"', '2"', '2 1/2"', '3"', '4"', '5"'],
  },
]
